name : Deploy to EC2

on:
  push:
    branches:
      - master

  jobs: 
    build : 
      runs-on: ubuntu-latest
      steps : 
        - name: Checkout
          uses: actions/checkout@v2

        - name: Decode and create .env
          run: echo "$ENV_VAR" | base64 -d > .env
          env : 
            ENV_VAR : ${{ secrets.ENV_VAR }}

        - name : Setup Node 
          uses : actions/setup-node@v4
          with : 
            node-version : 20
            cache : 'npm'    

        - name : Install Dependencies
          run : npm ci

        - name : Build project
          run : npm run build

        - name : Package application 
          run  : tar --exclude=.git --exclude=develop.tar -cvzf develop.tar .

        - name : Upload artifact  
          uses  : actions/upload-artifact@v4
          with :
            name : develop-tar
            path : develop.tar    
      
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: develop-tar

        - name: Copy files to server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ubuntu
            key: ${{ secrets.MY_SSH_KEY }}
            source: "develop.tar"
            target: "/home/ubuntu/"

        - name: Run remote script
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ubuntu
            key: ${{ secrets.MY_SSH_KEY }}
            script: "sh myScript.sh"        