name : Deploy to EC2

on:
  push:
    branches:
      - master

jobs: 
  build : 
    runs-on: ubuntu-latest
    steps : 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env file
        run: echo "${{ secrets.ENV_VAR }}" > .env


      - name : Setup Node 
        uses : actions/setup-node@v4
        with : 
          node-version : 20
          cache : 'npm'    

      - name : Install Dependencies
        run : npm ci

      - name : Build project
        run : npm run build

      - name : check disk space
        run : df -h

      - name: Package application
        run: sudo tar --exclude=develop.tar --ignore-failed-read -cvzf develop.tar -C . . 


      - name : Upload artifact  
        uses  : actions/upload-artifact@v4
        with :
          name : develop-tar
          path : develop.tar    
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: develop-tar

      - name: List files before transfer
        run: ls -lah

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.MY_SSH_KEY }}
          source: "develop.tar"
          target: "/home/ubuntu/"
          debug: true

      - name: Verify file transfer on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.MY_SSH_KEY }}
          script: |
            echo "Listing files in /home/ubuntu/ after transfer:"
            ls -lah /home/ubuntu/

      - name : Extract files
        uses : appleboy/ssh-action@master
        with : 
          host : ${{ secrets.SERVER_HOST }}
          username : ubuntu
          key : ${{ secrets.MY_SSH_KEY }}
          script : |
            rm -rf /home/ubuntu/demo 
            mkdir /home/ubuntu/demo
            tar -xvzf /home/ubuntu/develop.tar -C /home/ubuntu/demo
            rm /home/ubuntu/develop.tar

      - name: Run remote script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.MY_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /home/ubuntu/demo
            pm2 start --name demo npm -- start      